CREATE DATABASE IF NOT EXISTS poc_crm;

use poc_crm;

CREATE TABLE IF NOT EXISTS company(
    name VARCHAR(255) NOT NULL UNIQUE,
    domain_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS contact(
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    company_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    foreign Key (company_name) REFERENCES company(name)
);

CREATE TABLE IF NOT EXISTS deal (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    stage SMALLINT NOT NULL DEFAULT 0,
    closing_date DATE,
    lost_reason VARCHAR(400),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    foreign Key (company_name) REFERENCES company(name)

);

CREATE TABLE IF NOT EXISTS activity (
    id INT AUTO_INCREMENT PRIMARY KEY,
    due_date DATE NOT NULL,
    type VARCHAR(255) NOT NULL,
    identifier VARCHAR(255) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    cancel_reason VARCHAR(400),
    result VARCHAR(400),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);